[common]
audio_output_frequency = 48000
mute_audio = false
audio_sync = true
audio_dynamic_resampling_ratio = true
audio_buffer_size = 2048
audio_hardware_queue_size = 256
audio_gain_db = 0.0
save_path = "EmulatorFolder"
custom_save_path = ""
state_path = "EmulatorFolder"
custom_state_path = ""
launch_in_fullscreen = true
initial_window_size = 5
wgpu_backend = "Auto"
wgpu_power_preference = "HighPerformance"
vsync_mode = "Enabled"
frame_time_sync = true
auto_prescale = true
prescale_width = 3
prescale_height = 3
scanlines_enabled = false
scanlines_brightness = 0.8
force_integer_height_scaling = false
filter_mode = "Linear"
supersample_minification = true
preprocess_shader = "None"
anti_dither_shader = "None"
frame_rotation = "None"
load_recent_state_at_launch = false
fast_forward_multiplier = 2
rewind_buffer_length_seconds = 10
pause_emulator = "EmulatorLosesFocus"
hide_mouse_cursor = "Fullscreen"
cheats_enabled = false
cheats_path = "EmulatorFolder"
cheats_custom_path = ""

[common.ntsc]
brightness = 1.0
saturation = 1.0
gamma = 2.2

[smsgg]
remove_sprite_limit = false
sms_aspect_ratio = "Ntsc"
gg_aspect_ratio = "GgLcd"
sms_timing_mode = "Ntsc"
sms_model = "Sms2"
sms_crop_vertical_border = true
sms_crop_left_border = false
gg_frame_blending = false
gg_use_sms_resolution = false
fm_sound_unit_enabled = true
z80_divider = 15
allow_opposing_joypad_directions = false
sms_boot_from_bios = false
gg_boot_from_bios = false

[genesis]
allow_opposing_joypad_directions = false
aspect_ratio = "Auto"
force_square_pixels_in_h40 = false
adjust_aspect_ratio_in_2x_resolution = true
anamorphic_widescreen = false
remove_sprite_limits = false
m68k_clock_divider = 7
non_linear_color_scale = true
deinterlace = true
render_vertical_border = false
render_horizontal_border = false
plane_a_enabled = true
plane_b_enabled = true
window_enabled = true
backdrop_enabled = true
sprites_enabled = true
quantize_ym2612_output = true
opn2_busy_behavior = "Ym3438"
emulate_ym2612_ladder_effect = true
genesis_lpf_enabled = true
genesis_lpf_cutoff = 3390
ym2612_2nd_lpf_enabled = false
ym2612_2nd_lpf_cutoff = 6725
ym2612_channels_enabled = [
    true,
    true,
    true,
    true,
    true,
    true,
]
ym2612_enabled = true
psg_enabled = true
ym2612_volume_adjustment_db = 0.0
psg_volume_adjustment_db = 0.0

[sega_cd]
per_region_bios = true
pcm_interpolation = "None"
enable_ram_cartridge = true
load_disc_into_ram = false
disc_drive_speed = 1
sub_cpu_divider = 4
pcm_lpf_enabled = true
pcm_lpf_cutoff = 7973
apply_genesis_lpf_to_pcm = false
apply_genesis_lpf_to_cd_da = false
pcm_enabled = true
cd_audio_enabled = true
pcm_volume_adjustment_db = 0.0
cd_volume_adjustment_db = 0.0

[sega_32x]
sh2_clock_multiplier = 3
video_out = "Combined"
apply_genesis_lpf_to_pwm = true
darken_genesis_colors = true
color_tint = "None"
show_high_priority = true
show_low_priority = true
void_color_type = "Direct"
void_palette_index = 0
void_direct = [
    0,
    0,
    0,
]
void_direct_priority = false
pwm_resampling = "WindowedSinc"
pwm_enabled = true
pwm_volume_adjustment_db = 0.0

[nes]
forced_timing_mode = "Ntsc"
aspect_ratio = "Ntsc"
ntsc_crop_vertical_overscan = true
remove_sprite_limit = false
pal_black_border = false
silence_ultrasonic_triangle_output = false
audio_resampler = "WindowedSinc"
audio_60hz_hack = false
allow_opposing_joypad_directions = false
dma_dummy_joy_reads = true
palette = "UFBQAB2OCQe5LwC0VQCAawA0aQAATxEAJykAAz4AAEkAAEYAADVEAAAAAAAAAAAAnJycAE37Kyj/ag7/pQTnxwdywxkJmzkAXWAAIIEAAJIAAI0aAHOKAAAAAAAAAAAA////PaP/enb/xVT//0T//0nP/2NM/YsAtroAbOAANPQGGu1kHdDqPDw8AAAAAAAA////rNn/x8b/57f//6///7Lr/72z/s+G4eNuwfNxp/qNmfi+m+z3q6urAAAAAAAAVzQvAAtkDACLMQCJVQBfawAhawAAUQcAKxkACCkAADAAACsAABslAAAAAAAAAAAAqHBoBi26MRL1bQHypgCyxwBSxw4AnyYAZEQAKV4AA2kAAGICAElYAQAAAAAAAAAA/8K4SXL/hE//zDX//yr//zCc/0gv/2kAwo4AeqwAQ7oAJ7I2KJWlQiQgAAAAAAAA/8K4uqHd1ZH29IX0/3/Z/4Ks/418/5xV8KxA0blBt79YqbuAqq+wt3x1AAAAAAAAK04gABtdAAd/EwB4MABLRAARRAAAMBEAEigAAD0AAEkAAEMAADIiAAAAAAAAAAAAYZlPAEqtDSfhOw3XaQOTiAc3iBkAaTgAOV4AC38AAJEAAIkAAG9TAAAAAAAAAAAArfuVF5/+RHT/gFL/t0Hi2kh32mITtooAfLcAQd0AFvIAAukrAsqWHToUAAAAAAAArfuVatW+gMLUm7PQsauzv6+Iv7pasMw3mN8mfu8pafdAXfRmXeeVbahaAAAAAAAANDUdAAtUAABzGABvMwBKRwAQRwAANAgAFxgAACgAADAAACsAABwfAAAAAAAAAAAAcXFKAC6fFRTPQwPKbgCRjgA1jg8AbycAQUQAFF0AAGoAAGIAAElNAAAAAAAAAAAAw8SOJnTvVFH/jjf/wize5jJz5UoQwmoAio4AUawAJrsADbMlDpaPJSURAAAAAAAAw8SOfqO0lJPJrYfGw4Gt0oSC0ZBVw541rK0kkromfsA6cL1gcbGOfX5VAAAAAAAAODdtABOaBAPEIgC9QQCLUgBDTQADNQQAExQAACcAADIAADEOACVUAAAAAAAAAAAAd3XMADv/IR7/VAb/hAD5ngCLlwkhciAAOz0ADFwAAG0AAGs2AFikAAAHAAAAAAAAy8r/LIP/Y1//oj//2i//+DD48UN4xmMdhogASawAHcAtCr6SDqf/KCdVAAAAAAAAy8r/haz/n5z/uo7/0Yb/3Yf/25DsyZ++r6+mlL6qfsbHc8X3drv/hILcAAAAAAAAOypBAAlqBgCSIwCOQABmUAAsTgAANgEAFBEAAB8AACcAACUAABkqAAAAAAAAAAAAfGCFACjEJQ7/VQD6ggC/nABkmQQQcxoAPDYAEE8AAFsAAFcOAERhAAAAAAAAAAAA06zfMWj/aUX/pSz/2iH/+CW59TdPylYBiXoAUJcAJaYFEaFPE4q4KhwvAAAAAAAA06zfjJD+poD/v3T/1m/64nDP4Xmhz4h3tJdhm6Rjhqp6e6iifJ7QiWyTAAAAAAAAJjc5ABJnAAKIEgCBLgBUPgAcPAAAKgQADhQAACcAADIAAC8AACMwAAAAAAAAAAAAWXR4ADm/Cx3xOQbnZgCifwBLfAoBXyAAMjwABlsAAG0AAGkVAFVqAAAAAAAAAAAAo8jNFYD/QF3/ez3/sS3/zjGay0Q1qGMAc4cAOKsAD78HALpTAaO9GSYoAAAAAAAAo8jNY6rveJr/koz/qYTitIa4s4+LpZ5njq1UdbxYYMRxVsKYV7nGZYGFAAAAAAAALCwsAAlZAAB5FQB1MABQQAAZPgAAKwIAEBEAACAAACgAACUAABkkAAAAAAAAAAAAY2NjACqpEhDZPgDUagCagwBEgAYAYhwANTcAC1AAAFwAAFgHAEVWAAAAAAAAAAAAsbGxH2v/TEn/hTD/uCTx1iiM0joqr1kAeXwAQZkAGKgABqM7CI2hHh4eAAAAAAAAsbGxcJPRhYTnnnjltHPLwHShvn11sItTmZtBgadDbK1YYqt+Y6Kqb29vAAAAAAAA"

[nes.overscan]
top = 0
bottom = 0
left = 0
right = 0

[snes]
aspect_ratio = "Ntsc"
deinterlace = true
audio_interpolation = "Gaussian"
audio_60hz_hack = true
gsu_overclock_factor = 1
allow_opposing_joypad_directions = false

[game_boy]
force_dmg_mode = false
force_cgb_mode = false
pretend_to_be_gba = false
dmg_boot_rom = false
cgb_boot_rom = false
aspect_ratio = "SquarePixels"
gb_palette = "GreenTint"
gb_custom_palette = [
    [
    255,
    255,
    255,
],
    [
    170,
    170,
    170,
],
    [
    85,
    85,
    85,
],
    [
    0,
    0,
    0,
],
]
gbc_color_correction = "GbcLcd"
gbc_correction_gamma = 2.0
gba_correction_gamma = 3.2
frame_blending = true
audio_resampler = "WindowedSinc"
audio_60hz_hack = false
allow_opposing_joypad_directions = false

[game_boy_advance]
skip_bios_animation = false
aspect_ratio = "SquarePixels"
color_correction = "GbaLcd"
color_correction_gamma = 3.2
frame_blending = true
audio_interpolation = "NearestNeighbor"
psg_low_pass = false
pulse_1_enabled = true
pulse_2_enabled = true
wavetable_enabled = true
noise_enabled = true
pcm_a_enabled = true
pcm_b_enabled = true
allow_opposing_joypad_directions = false
solar_brightness_step = 5
solar_min_brightness = 23
solar_max_brightness = 175

[pc_engine]
region = "TurboGrafx16"
aspect_ratio = "Ntsc"
palette = "PceComposite"
crop_overscan = true
remove_sprite_limits = false
audio_resampler = "WindowedSinc"
allow_opposing_joypad_directions = false
allow_simultaneous_run_select = false

[input]
axis_deadzone = 8000

[[input.smsgg.mapping_1.p1.up]]
type = "Keyboard"
key = "Up"

[[input.smsgg.mapping_1.p1.left]]
type = "Keyboard"
key = "Left"

[[input.smsgg.mapping_1.p1.right]]
type = "Keyboard"
key = "Right"

[[input.smsgg.mapping_1.p1.down]]
type = "Keyboard"
key = "Down"

[[input.smsgg.mapping_1.p1.button1]]
type = "Keyboard"
key = "S"

[[input.smsgg.mapping_1.p1.button2]]
type = "Keyboard"
key = "A"

[input.smsgg.mapping_1.p2]

[input.smsgg.mapping_1.p1_turbo]

[input.smsgg.mapping_1.p2_turbo]

[[input.smsgg.mapping_1.pause]]
type = "Keyboard"
key = "Return"

[input.smsgg.mapping_2.p1]

[input.smsgg.mapping_2.p2]

[input.smsgg.mapping_2.p1_turbo]

[input.smsgg.mapping_2.p2_turbo]

[input.genesis]
p1_type = "SixButton"
p2_type = "SixButton"

[input.genesis.mapping_1.p1_turbo]

[input.genesis.mapping_1.p2_turbo]

[input.genesis.mapping_2.p1]

[input.genesis.mapping_2.p2]

[input.genesis.mapping_2.p1_turbo]

[input.genesis.mapping_2.p2_turbo]

[input.nes]
p2_type = "Gamepad"

[[input.nes.mapping_1.p1.up]]
type = "Keyboard"
key = "Up"

[[input.nes.mapping_1.p1.left]]
type = "Keyboard"
key = "Left"

[[input.nes.mapping_1.p1.right]]
type = "Keyboard"
key = "Right"

[[input.nes.mapping_1.p1.down]]
type = "Keyboard"
key = "Down"

[[input.nes.mapping_1.p1.a]]
type = "Keyboard"
key = "A"

[[input.nes.mapping_1.p1.b]]
type = "Keyboard"
key = "S"

[[input.nes.mapping_1.p1.start]]
type = "Keyboard"
key = "Return"

[[input.nes.mapping_1.p1.select]]
type = "Keyboard"
key = "Shift"

[input.nes.mapping_1.p2]

[input.nes.mapping_1.p1_turbo]

[input.nes.mapping_1.p2_turbo]

[[input.nes.mapping_1.zapper.fire]]
type = "Mouse"
button = "Left"

[[input.nes.mapping_1.zapper.force_offscreen]]
type = "Mouse"
button = "Right"

[input.nes.mapping_2.p1]

[input.nes.mapping_2.p2]

[input.nes.mapping_2.p1_turbo]

[input.nes.mapping_2.p2_turbo]

[input.nes.mapping_2.zapper]

[input.snes]
p2_type = "Gamepad"

[input.snes.mapping_1.p2]

[input.snes.mapping_1.p1_turbo]

[input.snes.mapping_1.p2_turbo]

[[input.snes.mapping_1.super_scope.fire]]
type = "Mouse"
button = "Left"

[[input.snes.mapping_1.super_scope.cursor]]
type = "Mouse"
button = "Right"

[[input.snes.mapping_1.super_scope.pause]]
type = "Mouse"
button = "Middle"

[[input.snes.mapping_1.super_scope.turbo_toggle]]
type = "Keyboard"
key = "T"

[input.snes.mapping_2.p1]

[input.snes.mapping_2.p2]

[input.snes.mapping_2.p1_turbo]

[input.snes.mapping_2.p2_turbo]

[input.snes.mapping_2.super_scope]

[[input.game_boy.mapping_1.up]]
type = "Keyboard"
key = "Up"

[[input.game_boy.mapping_1.left]]
type = "Keyboard"
key = "Left"

[[input.game_boy.mapping_1.right]]
type = "Keyboard"
key = "Right"

[[input.game_boy.mapping_1.down]]
type = "Keyboard"
key = "Down"

[[input.game_boy.mapping_1.a]]
type = "Keyboard"
key = "A"

[[input.game_boy.mapping_1.b]]
type = "Keyboard"
key = "S"

[[input.game_boy.mapping_1.start]]
type = "Keyboard"
key = "Return"

[[input.game_boy.mapping_1.select]]
type = "Keyboard"
key = "Shift"

[input.game_boy.mapping_2]

[input.game_boy.mapping_1_turbo]

[input.game_boy.mapping_2_turbo]

[[input.game_boy_advance.mapping_1.joypad.up]]
type = "Keyboard"
key = "Up"

[[input.game_boy_advance.mapping_1.joypad.left]]
type = "Keyboard"
key = "Left"

[[input.game_boy_advance.mapping_1.joypad.right]]
type = "Keyboard"
key = "Right"

[[input.game_boy_advance.mapping_1.joypad.down]]
type = "Keyboard"
key = "Down"

[[input.game_boy_advance.mapping_1.joypad.a]]
type = "Keyboard"
key = "A"

[[input.game_boy_advance.mapping_1.joypad.b]]
type = "Keyboard"
key = "S"

[[input.game_boy_advance.mapping_1.joypad.l]]
type = "Keyboard"
key = "Q"

[[input.game_boy_advance.mapping_1.joypad.r]]
type = "Keyboard"
key = "W"

[[input.game_boy_advance.mapping_1.joypad.start]]
type = "Keyboard"
key = "Return"

[[input.game_boy_advance.mapping_1.joypad.select]]
type = "Keyboard"
key = "Shift"

[input.game_boy_advance.mapping_1.solar]

[input.game_boy_advance.mapping_2.joypad]

[input.game_boy_advance.mapping_2.solar]

[input.game_boy_advance.mapping_1_turbo.joypad]

[input.game_boy_advance.mapping_1_turbo.solar]

[input.game_boy_advance.mapping_2_turbo.joypad]

[input.game_boy_advance.mapping_2_turbo.solar]

[[input.pc_engine.mapping_1.p1.up]]
type = "Keyboard"
key = "Up"

[[input.pc_engine.mapping_1.p1.left]]
type = "Keyboard"
key = "Left"

[[input.pc_engine.mapping_1.p1.right]]
type = "Keyboard"
key = "Right"

[[input.pc_engine.mapping_1.p1.down]]
type = "Keyboard"
key = "Down"

[[input.pc_engine.mapping_1.p1.button1]]
type = "Keyboard"
key = "A"

[[input.pc_engine.mapping_1.p1.button2]]
type = "Keyboard"
key = "S"

[[input.pc_engine.mapping_1.p1.run]]
type = "Keyboard"
key = "Return"

[[input.pc_engine.mapping_1.p1.select]]
type = "Keyboard"
key = "Shift"

[input.pc_engine.mapping_1.p2]

[input.pc_engine.mapping_1.p1_turbo]

[input.pc_engine.mapping_1.p2_turbo]

[input.pc_engine.mapping_2.p1]

[input.pc_engine.mapping_2.p2]

[input.pc_engine.mapping_2.p1_turbo]

[input.pc_engine.mapping_2.p2_turbo]

[[input.hotkeys.mapping_1.power_off]]
type = "Keyboard"
key = "Escape"

[[input.hotkeys.mapping_1.toggle_fullscreen]]
type = "Keyboard"
key = "F"

[[input.hotkeys.mapping_1.save_state]]
type = "Keyboard"
key = "F2"

[[input.hotkeys.mapping_1.load_state]]
type = "Keyboard"
key = "F4"

[[input.hotkeys.mapping_1.next_save_state_slot]]
type = "Keyboard"
key = "F7"

[[input.hotkeys.mapping_1.prev_save_state_slot]]
type = "Keyboard"
key = "F6"

[[input.hotkeys.mapping_1.soft_reset]]
type = "Keyboard"
key = "F8"

[[input.hotkeys.mapping_1.hard_reset]]
type = "Keyboard"
key = "F9"

[[input.hotkeys.mapping_1.pause]]
type = "Keyboard"
key = "P"

[[input.hotkeys.mapping_1.step_frame]]
type = "Keyboard"
key = "K"

[[input.hotkeys.mapping_1.fast_forward]]
type = "Keyboard"
key = "L"

[[input.hotkeys.mapping_1.rewind]]
type = "Keyboard"
key = "Backspace"

[[input.hotkeys.mapping_1.open_debugger]]
type = "Keyboard"
key = "F11"

[input.hotkeys.mapping_2]

[list_filters]
master_system = true
game_gear = true
sg_1000 = true
genesis = true
sega_cd = true
sega_32x = true
nes = true
snes = true
game_boy = true
game_boy_color = true
game_boy_advance = true
pc_engine = true

[[input.snes.mapping_1.p1.up]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Up"

[[input.snes.mapping_1.p1.left]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Left"

[[input.snes.mapping_1.p1.right]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Right"

[[input.snes.mapping_1.p1.down]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Down"

[[input.snes.mapping_1.p1.a]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 1"

[[input.snes.mapping_1.p1.b]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 0"

[[input.snes.mapping_1.p1.x]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 3"

[[input.snes.mapping_1.p1.y]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 2"

[[input.snes.mapping_1.p1.l]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 4"

[[input.snes.mapping_1.p1.r]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 5"

[[input.snes.mapping_1.p1.start]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 7"

[[input.snes.mapping_1.p1.select]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 6"

[[input.hotkeys.mapping_1.exit]]
type = "Keyboard"
key = "Escape"

[[input.genesis.mapping_1.p1.up]]
type = "Gamepad"
gamepad_idx = 1
action = "Hat 0 Up"

[[input.genesis.mapping_1.p1.left]]
type = "Gamepad"
gamepad_idx = 1
action = "Hat 0 Left"

[[input.genesis.mapping_1.p1.right]]
type = "Gamepad"
gamepad_idx = 1
action = "Hat 0 Right"

[[input.genesis.mapping_1.p1.down]]
type = "Gamepad"
gamepad_idx = 1
action = "Hat 0 Down"

[[input.genesis.mapping_1.p1.a]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 2"

[[input.genesis.mapping_1.p1.b]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 0"

[[input.genesis.mapping_1.p1.c]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 1"

[[input.genesis.mapping_1.p1.x]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 4"

[[input.genesis.mapping_1.p1.y]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 3"

[[input.genesis.mapping_1.p1.z]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 5"

[[input.genesis.mapping_1.p1.start]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 7"

[[input.genesis.mapping_1.p1.mode]]
type = "Gamepad"
gamepad_idx = 1
action = "Button 6"

[[input.genesis.mapping_1.p2.up]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Up"

[[input.genesis.mapping_1.p2.left]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Left"

[[input.genesis.mapping_1.p2.right]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Right"

[[input.genesis.mapping_1.p2.down]]
type = "Gamepad"
gamepad_idx = 0
action = "Hat 0 Down"

[[input.genesis.mapping_1.p2.a]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 2"

[[input.genesis.mapping_1.p2.b]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 0"

[[input.genesis.mapping_1.p2.c]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 1"

[[input.genesis.mapping_1.p2.x]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 4"

[[input.genesis.mapping_1.p2.y]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 3"

[[input.genesis.mapping_1.p2.z]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 5"

[[input.genesis.mapping_1.p2.start]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 7"

[[input.genesis.mapping_1.p2.mode]]
type = "Gamepad"
gamepad_idx = 0
action = "Button 6"

